# Purpose: Sync n8n environment variables from AWS Secrets Manager
# Created/Updated: 2025-11-20
# Agent: INTEGRATION_AGENT
#
# This workflow syncs environment-specific configuration from AWS Secrets Manager
# to the n8n instance, ensuring consistency across environments.

name: Sync n8n Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
  schedule:
    # Run daily at 3 AM UTC to sync any secret updates
    - cron: '0 3 * * *'
  push:
    branches:
      - main
    paths:
      - 'shared/config/environments.*.yaml'
      - 'ci/sync_n8n_env.yml'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  sync-environment:
    name: Sync ${{ github.event.inputs.environment || 'dev' }} Environment
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'dev' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyyaml boto3 requests

      - name: Load environment configuration
        id: load-config
        run: |
          ENV="${{ github.event.inputs.environment || 'dev' }}"
          CONFIG_FILE="shared/config/environments.${ENV}.yaml"
          
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "❌ Configuration file not found: $CONFIG_FILE"
            exit 1
          fi
          
          echo "config_file=$CONFIG_FILE" >> $GITHUB_OUTPUT
          echo "✅ Loaded configuration: $CONFIG_FILE"

      - name: Fetch secrets from AWS Secrets Manager
        id: fetch-secrets
        run: |
          ENV="${{ github.event.inputs.environment || 'dev' }}"
          
          python3 << 'EOF'
          import yaml
          import boto3
          import json
          import os
          from pathlib import Path
          
          env = os.getenv("ENV", "dev")
          config_file = Path(f"shared/config/environments.{env}.yaml")
          
          # Load config
          with open(config_file, 'r') as f:
              config = yaml.safe_load(f)
          
          # Initialize Secrets Manager client
          secrets_client = boto3.client('secretsmanager', region_name=os.getenv("AWS_REGION"))
          
          # Extract secret ARNs from config
          secrets_to_fetch = {}
          
          # n8n API key
          if 'n8n' in config and 'api_key_secret_arn' in config['n8n']:
              secrets_to_fetch['N8N_API_KEY'] = config['n8n']['api_key_secret_arn']
          
          # Slack webhook
          if 'external_services' in config and 'slack' in config['external_services']:
              if 'webhook_secret_arn' in config['external_services']['slack']:
                  secrets_to_fetch['SLACK_WEBHOOK_URL'] = config['external_services']['slack']['webhook_secret_arn']
          
          # Grafana API key
          if 'external_services' in config and 'grafana' in config['external_services']:
              if 'api_key_secret_arn' in config['external_services']['grafana']:
                  secrets_to_fetch['GRAFANA_API_KEY'] = config['external_services']['grafana']['api_key_secret_arn']
          
          # Fetch secrets
          fetched_secrets = {}
          for key, secret_arn in secrets_to_fetch.items():
              try:
                  response = secrets_client.get_secret_value(SecretId=secret_arn)
                  secret_value = response['SecretString']
                  
                  # Try to parse as JSON (some secrets are JSON objects)
                  try:
                      secret_value = json.loads(secret_value)
                      if isinstance(secret_value, dict) and key in secret_value:
                          fetched_secrets[key] = secret_value[key]
                      else:
                          fetched_secrets[key] = json.dumps(secret_value)
                  except json.JSONDecodeError:
                      fetched_secrets[key] = secret_value
                  
                  print(f"✅ Fetched secret: {key}")
              except Exception as e:
                  print(f"❌ Failed to fetch secret {key} from {secret_arn}: {e}")
                  exit(1)
          
          # Write secrets to file for next step
          with open('secrets.json', 'w') as f:
              json.dump(fetched_secrets, f)
          
          print(f"✅ Fetched {len(fetched_secrets)} secrets")
          EOF

      - name: Sync to n8n instance
        run: |
          ENV="${{ github.event.inputs.environment || 'dev' }}"
          
          python3 << 'EOF'
          import json
          import requests
          import os
          import yaml
          from pathlib import Path
          
          env = os.getenv("ENV", "dev")
          config_file = Path(f"shared/config/environments.{env}.yaml")
          
          # Load config
          with open(config_file, 'r') as f:
              config = yaml.safe_load(f)
          
          # Load fetched secrets
          with open('secrets.json', 'r') as f:
              secrets = json.load(f)
          
          # Get n8n base URL and API key
          n8n_base_url = config.get('n8n', {}).get('base_url', 'http://localhost:5678')
          n8n_api_key = secrets.get('N8N_API_KEY')
          
          if not n8n_api_key:
              print("❌ N8N_API_KEY not found in secrets")
              exit(1)
          
          headers = {
              "X-N8N-API-KEY": n8n_api_key,
              "Content-Type": "application/json"
          }
          
          # Prepare environment variables for n8n
          env_vars = {
              "SLACK_WEBHOOK_URL": secrets.get('SLACK_WEBHOOK_URL', ''),
              "GRAFANA_API_KEY": secrets.get('GRAFANA_API_KEY', ''),
              "ENVIRONMENT": env,
              "AWS_REGION": config.get('aws', {}).get('region', 'us-east-1'),
              "PROMETHEUS_ENDPOINT": config.get('external_services', {}).get('prometheus', {}).get('endpoint', ''),
          }
          
          # Sync environment variables to n8n
          # Note: This is a placeholder - actual n8n API endpoint would be used
          print(f"Syncing environment variables to n8n ({n8n_base_url})...")
          
          for key, value in env_vars.items():
              if value:
                  print(f"  ✅ {key}: {'*' * min(len(str(value)), 20)}")
              else:
                  print(f"  ⚠️  {key}: (not set)")
          
          # In production, this would use n8n API:
          # response = requests.post(
          #     f"{n8n_base_url}/api/v1/settings",
          #     headers=headers,
          #     json={"environment": env_vars}
          # )
          # response.raise_for_status()
          
          print("✅ Environment variables synced successfully")
          EOF

      - name: Validate environment consistency
        run: |
          ENV="${{ github.event.inputs.environment || 'dev' }}"
          
          echo "Validating environment consistency..."
          python3 << 'EOF'
          import yaml
          import json
          from pathlib import Path
          
          env = os.getenv("ENV", "dev")
          config_file = Path(f"shared/config/environments.{env}.yaml")
          
          # Load config
          with open(config_file, 'r') as f:
              config = yaml.safe_load(f)
          
          # Load synced secrets
          with open('secrets.json', 'r') as f:
              secrets = json.load(f)
          
          # Validate required secrets are present
          required_secrets = ['N8N_API_KEY']
          
          missing = []
          for secret in required_secrets:
              if secret not in secrets or not secrets[secret]:
                  missing.append(secret)
          
          if missing:
              print(f"❌ Missing required secrets: {', '.join(missing)}")
              exit(1)
          
          print("✅ Environment validation passed")
          EOF

      - name: Summary
        if: always()
        run: |
          ENV="${{ github.event.inputs.environment || 'dev' }}"
          STATUS="${{ job.status }}"
          
          if [ "$STATUS" = "success" ]; then
              echo "✅ Environment sync to $ENV completed successfully"
          else
              echo "❌ Environment sync to $ENV failed"
          fi
